import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <Link href="/" style={{ color: "black", textDecoration: "none", fontSize: "18px", marginRight: "20px" }}>
            Home
          </Link>
          <Link href="/courses" style={{ color: "black", textDecoration: "none", fontSize: "18px", marginRight: "20px" }}>
            Courses
          </Link>
          <Link href="/signup" style={{ color: "black", textDecoration: "none", fontSize: "18px", marginRight: "20px" }}>
            Sign Up
          </Link>
          <Link href="/login" style={{ color: "black", textDecoration: "none", fontSize: "18px" }}>
            Login
          </Link>
          <Link href="/profile" style={{ color: "black", textDecoration: "none", fontSize: "18px", marginLeft: "20px" }}>Profile</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}