'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Déplacez les métadonnées dans un fichier séparé puisque nous utilisons 'use client'
// Cette partie ne fonctionnera pas dans un composant client
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const router = useRouter();

  // Vérifier l'état de connexion au montage du composant
  useEffect(() => {
    const token = localStorage.getItem('token');
    setIsLoggedIn(!!token);
  }, []);

  // Gérer la déconnexion
  const handleLogout = () => {
    localStorage.removeItem('token');
    setIsLoggedIn(false);
    router.push('/login');
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-600 p-4 shadow-md">
          <div className="max-w-7xl mx-auto flex justify-between items-center">
            <div>
              <Link
                href="/"
                className="text-white text-2xl font-bold hover:text-gray-300"
              >
                Home
              </Link>
            </div>
            <div className="space-x-6">
              <Link
                href="/courses"
                className="text-white text-lg hover:text-gray-300"
              >
                Courses
              </Link>
              
              {/* Afficher les liens en fonction de l'état de connexion */}
              {isLoggedIn ? (
                <>
                  <Link
                    href="/profile"
                    className="text-white text-lg hover:text-gray-300"
                  >
                    Profile
                  </Link>
                  <button
                    onClick={handleLogout}
                    className="text-white text-lg hover:text-gray-300 bg-transparent border-none cursor-pointer"
                  >
                    Logout
                  </button>
                </>
              ) : (
                <>
                  <Link
                    href="/signup"
                    className="text-white text-lg hover:text-gray-300"
                  >
                    Sign Up
                  </Link>
                  <Link
                    href="/login"
                    className="text-white text-lg hover:text-gray-300"
                  >
                    Login
                  </Link>
                </>
              )}
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}